# Generated by Django 3.1.7 on 2021-03-19 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicename', models.CharField(default='', max_length=100, verbose_name='nicename')),
                ('description', models.CharField(default='', max_length=100, verbose_name='description')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(blank=True, related_name='tags', to='api.Post')),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicename', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Suspended', 'Suspended'), ('Removed', 'Removed'), ('Pending', 'Pending')], default='Draft', max_length=20, verbose_name='nicename')),
                ('description', models.CharField(default='', max_length=100, verbose_name='description')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(blank=True, related_name='statuses', to='api.Post')),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
    ]
