# Generated by Django 3.1.7 on 2021-03-24 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_status_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=200, verbose_name='description')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicename', models.CharField(default='', max_length=100, verbose_name='nicename')),
                ('description', models.CharField(default='', max_length=100, verbose_name='description')),
                ('link', models.URLField(default='https://', verbose_name='link')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'social_links',
            },
        ),
    ]
