# Generated by Django 3.1.7 on 2021-03-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210324_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='description',
        ),
    ]
