# Generated by Django 3.1.7 on 2021-03-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_status_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='alt text'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(default='https://source.unsplash.com/random', verbose_name='image'),
        ),
    ]
